### ISSUE TITLE
Day2 scripts: project export does not export PVCs configurations

### ISSUE THREAD

**Issue by alberttwong** [openshift/openshift-ansible-contrib#958] opened 2018-03-01 19:58 UTC
# BUG REPORT INFO

### Environment

- AWS but I think it's applicable to all environments
 
- OCP 3.7

**Comment by e-minguez** [comment] 2018-03-01 20:58
Thanks for opening the issue Albert. It should do it ([here](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/day2ops/scripts/project_export.sh#L189-L203))
Do you mind to provide any example where it didn't worked?
Thanks!

**Comment by alberttwong** [comment] 2018-03-02 22:26
Need to do a delta on jsons but I think we shouldn't delete `.spec.volumeName`

**Comment by e-minguez** [comment] 2018-03-05 16:23
The thing is the volume will be deleted/recycled/retained depending on the volume [reclaiming configuration](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming), once the PVC is deleted, and a user cannot specify the volume the PVC is going to be attached to. Also, if the user is migrating from one environment to another, the volume most likely won't be present in the "new" environment.

**Comment by alberttwong** [comment] 2018-03-05 20:09
Then the scripts have a gap.  The gap is that it only project export and imports projects that don't have persistent volumes attached to pods.   

The RH Storage Wolf Pack team just build a working POC to replicate OCP PV volumes, backed by Cluster, from one OCP cluster to another OCP cluster.    As a result, if the user sets the volume to retained, the volumes will be present in the "new" environment.    We have also tested that if we leave the pvcs.json configs there, the pod will try to remount until it "sees" the volume.   I'd love to get this into your day2 scripts if possible.

**Comment by e-minguez** [comment] 2018-03-09 11:31
I see. Then the issue is the pvcs are not exported with the attachment information. I've tried to cover that use case [here](https://github.com/openshift/openshift-ansible-contrib/pull/965).
Do you mind to take a look @alberttwong ? Thanks!

**Comment by alberttwong** [comment] 2018-03-12 20:46
What do you mean by take a look?   Try it in the DR scenario or just do it with a container with a PV attached and move it between clusters?

**Comment by alberttwong** [comment] 2018-05-16 16:32
@e-minguez Just wanted to follow up on this.  What exactly do you want me to do?

**Comment by e-minguez** [comment] 2018-05-18 11:03
So, you requested the script to export pvcs with attachment included data which I did [here](https://github.com/openshift/openshift-ansible-contrib/pull/965/files).
Now the script exports 
* `${PROJECT}/pvcs_attachment.json` that includes attachment information in case you needed
* `${PROJECT}/pvcs.json` as before

**Comment by e-minguez** [comment] 2019-10-14 05:03
Those scripts are no longer updated and are not supported. Closing this. Thanks

**Closed** 2019-10-14 05:03 UTC
Labels: day2ops
