### ISSUE TITLE
etcd certs do not use fully qualified internal domain name

### ISSUE THREAD

**Issue by kfp** [openshift/openshift-ansible-contrib#930] opened 2018-02-08 15:59 UTC
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one): Bug Report

# BUG REPORT INFO

### Environment

- **Cloud provider**:  RHV

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
Linux 3.10.0-693.17.1.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

- **Version of Ansible** (`ansible --version`):  
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

- **Version of Jinja** (`pip freeze | grep -i jinja`):  

- **Version of Shade** (`pip freeze | grep -i shade`):  

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  48644bd

**Copy of inventory files and custom variables used (please omit your secrets!)**:  
dynamic inventory: https://gist.github.com/kfp/caadd9922ccfdaaab6e84ebee9695e9a

**Command used to invoke ansible**:  
ansible-playbook -e@ocp-vars.yaml playbooks/openshift-validate.yaml

**Output of ansible run**:  

...
When trying to validate the openshift install the following error is received:
Error:  client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate is valid for openshift-master-0, not openshift-master-0.internal.host.com

error #0: x509: certificate is valid for openshift-master-0, not openshift-master-0.internal.host.com

**Anything else do we need to know**:  

I suspect something in the inventory is not getting mapped correctly to the openshift installer. Presumably the internal FQDN should be used here. I'm going to try to look through the playbooks and see if I can spot the disconnect.

**Comment by smapjb** [comment] 2018-02-28 09:02
I also hit this (and other problems) This one seems to be related to the ovirt dynamic inventory script. After the machines are provisioned the ansible dynamic inventory script reports just the short hostname for the fqdn.

I restarted the ovirt-guest agent to at least get it to report correctly the fqdn

`ansible -i hosts all -m systemd -a "name=ovirt-guest-agent state=restarted" -f 8`

I have hit other problems so have not confirmed this fixes the issue.. but thought I would highlight it here.

The other issue is that once docker is installed the first interface returned by the dynamic inventory script is docker0 so you are left with a non-routable IP !!

**Comment by cwilkers** [comment] 2018-03-02 22:11
I've just merged a fix for the node names vs host names disagreeing.

I've not seen the problem with the `docker0` overriding `eth0`, but I generally use the `output-dns.yaml` playbook to create nsupdate files for bind right after VM creation.

**Comment by cwilkers** [comment] 2018-04-08 16:27
I'm calling this closed with the host name fix. Work on 3.9 is going to change much of this.

**Closed by cwilkers** 2018-04-08 16:27 UTC
Labels: rhv
