### ISSUE TITLE
AWS ansible error: ERROR! no action detected in task

### ISSUE THREAD

**Issue by kerin** [openshift/openshift-ansible-contrib#135] opened 2016-12-05 11:53 UTC
I'm trying to deploy the `aws-ansible` reference architecture, and get this error when running `ose-on-aws.py`, seemingly when it tries to apply `playbooks/openshift-install.yaml`:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/prerequisite/tasks/main.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Gather facts
  ^ here
```

I've tried this on both Mac OSX and CentOS 7 in Vagrant (above). In both cases all dependencies are installed and `openshift-ansible` is checked out - although on OSX the destination path has to be changed to `/usr/local/share/...` due to OSX security policy on `/usr/share`.

**Comment by cooktheryan** [comment] 2016-12-05 17:10
@kerin are you attempting to install origin or openshift-enterprise?

**Comment by cooktheryan** [comment] 2016-12-06 20:56
I hope this helps https://gist.github.com/cooktheryan/479cdabf9136b975e709cce28357992f

 I ran through the setup but could not reproduce your error

**Comment by kerin** [comment] 2016-12-07 09:55
Thanks @cooktheryan - this was an Origin install. I did ultimately manage to proceed past that error, but I'm not clear what I actually did to get there. I think this was possibly related to Ansible caching something in my initial playbook runs, which failed due to SSH misconfiguration, but that's just a guess really.

**Comment by mcedica** [comment] 2017-01-21 06:09
I had the same issue on Mac OSX  after installing openshift-ansible in /usr/local/share/ansible due to the security policy on /usr/share
My problem was that I still had  symlinks pointing to /usr/share/ like
openshift_facts.py -> usr/share/ansible/openshift-ansible/roles/openshift_facts/library/openshift_facts.py 
Recreating the symlinks fixed this issue.

**Comment by cooktheryan** [comment] 2017-01-21 15:28
Thanks @mcedica 

I'm going to close this issue as now there is a resolution

**Closed by cooktheryan** 2017-01-21 15:28 UTC
Labels: aws
